### ISSUE TITLE
build is failing according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [jantman/pypi-download-stats#20]
see https://github.com/jantman/pypi-download-stats#pypi-download-stats

**Comment by jantman** [comment]
Ah, thanks. I've been ignoring that for a while. The build of the code is passing (see the [breakdown of build environments](https://travis-ci.org/jantman/pypi-download-stats)) but the sphinx doc build is failing.

I'll dig into this, thanks for pinging me about it.

**Comment by jantman** [comment]
Thanks for bringing my attention to this. Build was fixed by #21
